// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmF--MpWkIPenrvI6FzzunQvzMGnfzOAU',
    appId: '1:494415235430:web:fa5eeee518ecc589ad20a7',
    messagingSenderId: '494415235430',
    projectId: 'rumbawa-advmobprog',
    authDomain: 'rumbawa-advmobprog.firebaseapp.com',
    storageBucket: 'rumbawa-advmobprog.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE4FE6KNvQt6yQnz9wIGADEdE1SfNMbFM',
    appId: '1:494415235430:android:b84a5da7ad386057ad20a7',
    messagingSenderId: '494415235430',
    projectId: 'rumbawa-advmobprog',
    storageBucket: 'rumbawa-advmobprog.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6PIh9UvCNGADZYaP1qgJNgDIf6_CloMU',
    appId: '1:494415235430:ios:e926da6b95911424ad20a7',
    messagingSenderId: '494415235430',
    projectId: 'rumbawa-advmobprog',
    storageBucket: 'rumbawa-advmobprog.firebasestorage.app',
    iosBundleId: 'com.example.rumbawaAdvmobprog',
  );
}
